### ISSUE TITLE
Feature Request: Exclude directories

### ISSUE THREAD

**Issue by fleimgruber** [AurelienLourot/uncommitted#9]
Motivation: I just ran into this one
```
[py35] D:\>uncommitted -Luns .
Traceback (most recent call last):
  File "D:\Miniconda3_64\envs\py35\Scripts\uncommitted-script.py", line 11, in <module>
    load_entry_point('uncommitted', 'console_scripts', 'uncommitted')()
  File "d:\uncommitted\uncommitted\command.py", line 207, in main
    repos.update(find_repos(path))
  File "d:\uncommitted\uncommitted\command.py", line 70, in find_repositories_by_walking
    dir_inode = inode(os.path.join(dirpath, dirname))
  File "d:\uncommitted\uncommitted\command.py", line 61, in inode
    stats = os.stat(path)
PermissionError: [WinError 5] Access is denied: 'D:\\System Volume Information'
```

Now (possibly after recovering from the shock of spotting the OS part in the exception), these are some ideas on ways to circumvent this:
* Move all repos to a different subdirectory where I can make sure every directory is actually a valid repo
* Call uncommitted from another script which just swallows those and similar exceptions
* Use locate instead of `os.walk` and tell locate to exclude certain patterns (just an idea, not sure whether that is actually possible, though)
* Add a feature to uncommitted to ignore patterns or explicit directories/files from reading by specifying an exclude file, e.g. `--exclude-from exclude_list`

Of those, the last one would be my favourite, hence this FR. What do you think?

**Comment by AurelienLourot** [comment]
Hi @fleimgruber,

this is a good idea, but note that you can achieve the same result already by using GNU tools on Windows, e.g. in bash you can do:

```
$ ls --color=never | grep -v System | xargs uncommitted -Luns
```

This is because `uncommitted` accepts a list of directories as argument. In this case:
- `ls` lists all directories under `D:\` and passes this list to...
- `grep`, which removes from the list directories containing whose name contains `System` and passes this list to...
- `uncommitted`.

Thus implementing this feature would be a bit like reinventing the wheel (here the GNU tools), which you already get for free when installing git on Windows (it comes with Git Bash).

Would it be an option for you to use Git Bash?

**Comment by fleimgruber** [comment]
I like it. More *nix style and I keep Git Bash by my side anyways. For reference, this worked for me:

    \ls -Q | grep -v "[System|RECYCLE]" | xargs uncommitted -Luns
